# Generated by Django 5.1.5 on 2025-02-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short title for the subject', max_length=200)),
                ('header', models.CharField(help_text='The header text to display', max_length=200)),
                ('content', models.TextField(help_text='The paragraph text for the subject')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the subject', null=True, upload_to='subject_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
