# Generated by Django 5.1.5 on 2025-02-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(choices=[(1, 'Page 1'), (2, 'Page 2'), (3, 'Page 3'), (4, 'Page 4')], unique=True)),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='page_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
