# Generated by Django 5.0.6 on 2025-02-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='page_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(choices=[(1, 'Statistics'), (2, 'Public Speaking'), (3, 'Business'), (4, 'Psychology')], unique=True)),
                ('header', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='page_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Psychology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='page_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PublicSpeaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='page_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='page_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
