# Generated by Django 5.0.6 on 2025-02-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business_page_psychology_publicspeaking_statistics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Business'},
        ),
        migrations.AlterModelOptions(
            name='psychology',
            options={'verbose_name_plural': 'Psychology'},
        ),
        migrations.AlterModelOptions(
            name='publicspeaking',
            options={'verbose_name_plural': 'Public Speaking'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'Statistics'},
        ),
    ]
