# Generated by Django 5.0.6 on 2025-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_page_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='subText',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='psychology',
            name='subText',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicspeaking',
            name='subText',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subText',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
