# Generated by Django 5.0.6 on 2025-02-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_business_subtext_psychology_subtext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='subText',
            new_name='sub_text',
        ),
        migrations.RenameField(
            model_name='psychology',
            old_name='subText',
            new_name='sub_text',
        ),
        migrations.RenameField(
            model_name='publicspeaking',
            old_name='subText',
            new_name='sub_text',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='subText',
            new_name='sub_text',
        ),
    ]
