# Generated by Django 5.1.5 on 2025-03-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_subtext_business_sub_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('anything', models.TextField()),
            ],
        ),
    ]
